version: '3.7'

services:
  php:
    container_name: banger-php
    build: ./deployment/backend
    image: banger-php:latest
    volumes:
      - ./backend/:/application:delegated
      - ./deployment/backend/entrypoint-local.sh:/usr/local/bin/entrypoint.sh:delegated
      - ./deployment/backend/custom-php-dev.ini:/usr/local/etc/php/conf.d/custom-php.ini:delegated
    command: php-fpm
    depends_on:
      - redis
      - mysql
    restart: always

  php-cron:
    container_name: banger-cron
    restart: always
    image: banger-php:latest
    command: "php artisan schedule:run"
    depends_on:
      - php
    volumes:
      - ./backend/:/application:delegated
      - ./deployment/backend/entrypoint-cron.sh:/usr/local/bin/entrypoint.sh:delegated

  php-queue:
    restart: always
    image: banger-php:latest
    command: "php artisan queue:work"
    deploy:
      replicas: 2
    depends_on:
      - php
    volumes:
      - ./backend/:/application:delegated
      - ./deployment/backend/entrypoint-queue.sh:/usr/local/bin/entrypoint.sh:delegated

  vue:
    container_name: banger-vue
    build: ./deployment/frontend
    command: "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=1
      - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/:/frontend:delegated
      - ./deployment/frontend/entrypoint.sh:/usr/local/bin/entrypoint.sh:delegated

  mysql:
    image: mysql:latest
    container_name: banger-mysql
    volumes:
      - banger_db:/var/lib/mysql
    ports:
      - 3306:3306
    command: --max_allowed_packet=100M
    environment:
      - MYSQL_ROOT_PASSWORD=banger123
      - MYSQL_USER=banger
      - MYSQL_PASSWORD=banger123
      - MYSQL_DATABASE=banger
    restart: always

  echo:
    container_name: banger-echo
    build: ./deployment/echo
    depends_on:
      - redis
    ports:
      - "6001:6001"
    volumes:
      - ./deployment/echo/entrypoint.sh:/usr/local/bin/entrypoint.sh:delegated
      - ./deployment/echo/laravel-echo-server-dev.json:/usr/local/bin/laravel-echo-server.json:delegated
      - ./deployment/certbot/conf:/etc/letsencrypt:delegated

  nginx:
    container_name: banger-nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/default-local.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./backend:/application:delegated
      - ./frontend/public:/frontend:delegated
      - ./deployment/certbot/conf:/etc/letsencrypt:delegated
      - ./deployment/certbot/www:/var/www/certbot:delegated
      - ./deployment/nginx/ssl123:/ssl123:delegated
      - ./deployment/nginx/proxy.conf:/etc/nginx/proxy.conf:delegated
      - ./deployment/nginx/auth/htpasswd:/deployment/nginx/auth/htpasswd:delegated
    depends_on:
      - php
      - vue

  redis:
    container_name: banger-redis
    image: redis
    volumes:
      - redis_data:/data

  portainer:
      container_name: banger-portainer
      image: portainer/portainer
      ports:
      - "9000:9000"
      command: -H unix:///var/run/docker.sock
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock:delegated
      - portainer_data:/data:delegated

volumes:
    redis_data:
    portainer_data:
    banger_db:
