version: '3.7'

services:
  php:
    container_name: banger-php
    build: ./deployment/backend
    image: banger-php:latest
    volumes:
      - ./backend/:/application
      - ./deployment/backend/workers:/workers
      - ./deployment/backend/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./deployment/backend/custom-php-dev.ini:/usr/local/etc/php/conf.d/custom-php.ini
    command: php-fpm
    depends_on:
      - redis
    restart: always

  php-cron:
    container_name: banger-cron
    restart: always
    image: banger-php:latest
    command: "php artisan schedule:run"
    depends_on:
      - php
    volumes:
      - ./backend/:/application
      - ./deployment/backend/entrypoint-cron.sh:/usr/local/bin/entrypoint.sh

  php-queue:
    restart: always
    image: banger-php:latest
    command: "php artisan queue:work"
    deploy:
      replicas: 2
    depends_on:
      - php
    volumes:
      - ./backend/:/application
      - ./deployment/backend/entrypoint-queue.sh:/usr/local/bin/entrypoint.sh

  vue:
    container_name: banger-vue
    build: ./deployment/frontend
    command: "npm run prod"
    environment:
      NODE_ENV: production
    volumes:
      - ./frontend/:/frontend
      - ./deployment/frontend/entrypoint.sh:/usr/local/bin/entrypoint.sh

  echo:
    container_name: banger-echo
    build: ./deployment/echo
    depends_on:
      - redis
    ports:
      - "6001:6001"
    volumes:
      - ./deployment/echo/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./deployment/echo/laravel-echo-server-dev.json:/usr/local/bin/laravel-echo-server.json
      - ./deployment/certbot/conf:/etc/letsencrypt

  nginx:
    container_name: banger-nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/application
      - ./frontend/public:/frontend
      - ./deployment/certbot/conf:/etc/letsencrypt
      - ./deployment/certbot/www:/var/www/certbot
      - ./deployment/nginx/ssl123:/ssl123
      - ./deployment/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./deployment/nginx/auth/htpasswd:/deployment/nginx/auth/htpasswd
    depends_on:
      - php
      - vue

  redis:
    container_name: banger-redis
    image: redis
    volumes:
      - redis_data:/data

  portainer:
      container_name: banger-portainer
      image: portainer/portainer
      ports:
      - "9000:9000"
      command: -H unix:///var/run/docker.sock
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./deployment/certbot/conf:/etc/letsencrypt
#      - ./deployment/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --cert-name dev.bangergames.com; sleep 12h & wait $${!}; done;'"


volumes:
    redis_data:
    portainer_data:
